### ISSUE TITLE
Create room

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/Live-Peers#14]
**As a** mentor
**I want** to be able to add my students to my presentation
**So that** they can all contribute with their questions, and a moderator can cast my video for everyone in their location

+ [ ] #21 "Log in" to create a room
+ [ ] #15 Add room name
+ [ ] Clicking "create" generates shareable link to the URL of the room - see chat/AV page issues
