### ISSUE TITLE
View number of moderators/students online

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/Live-Peers#18]
**As a** mentor
**I want to** know how many students are online, and who they are 
**So that**:
+ I only begin my presentation when everyone is ready and online
+ I can review attendance metrics at a later date
+ I can easily see if someone drops offline - if this is a moderator, that whole class can't see my presentation any more and I probably need to find out what happened

+ [ ] #19 Small button in top right hand corner, indicating number of moderators online & number of students online 
+ [ ] #20 Clicking the button - a sidebar pops out, with a list of all the names
+ [ ] #26 Students need to join my room with their name, so that their name can be added to my list
