### ISSUE TITLE
Endpoint Tasks

### ISSUE THREAD

**Issue by njsfield** [foundersandcoders/Live-Peers#40]
Using this [boilerplate](https://github.com/foundersandcoders/Live-Peers/tree/serversocket-boilerplate) to begin with, issue #30 can be resolved by building the following modules

## Client Side
- [x] Client side [comms](https://github.com/foundersandcoders/Live-Peers/blob/master/public/js/comms.js]
- [x] Client side chat room handler

## Server Side
- [x] Socket Router ( checks where messages are going to and registers users, perhaps using switch statement  )
- [x] Socket Server ( takes socketserver and connects it to Socket Router)
- [x] Server Room Class ( to satisfy # 5 of issue #30, plus additional methods to check to see if users are already registered)
